name: Yijing Li
markdown: kramdown
theme: jekyll-theme-cayman
title: City Crime Change against COVID-19
description: Project site
show_downloads: false

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
